### ISSUE TITLE
No Ability to PreAuth or Capture, Refactor needed. 

### ISSUE THREAD

**Issue by johnnye** [thephpleague/omnipay-gocardless#1]
At the moment there is no ability to pre-auth, capture or cancel a GoCardless.

I'm working on a PR at the moment to fix this, I can just add the required methods. Or preferably I can submit a bigger tidy up of the code. 

I understand that big PRs are hard to manage, so maybe a 2 step approach would be better. 

Happy to take any approach with this.

**Comment by greydnls** [comment]
I'd prefer two separate PRs. One making additions, one doing cleanup. 

Thank you!

**Comment by johnnye** [comment]
Thanks, sounds reasonable to me.
